### ISSUE TITLE
Take care of wildcard subdomain

### ISSUE THREAD

**Issue by gehaxelt** [nahamsec/HostileSubBruteforcer#4]
Hi, 

when the website uses a wildcard subdomain, e.g `*.domain.tld` pointing to one webserver, your script detects every possible subdomain from the list:

```
[Fri Nov 13 13:59:58 2015] 301 0.internetwache.org ---> 95.143.172.58 
[Fri Nov 13 13:59:59 2015] 301 01.internetwache.org ---> 95.143.172.58 
[Fri Nov 13 14:00:00 2015] 301 02.internetwache.org ---> 95.143.172.58 
[Fri Nov 13 14:00:01 2015] 301 03.internetwache.org ---> 95.143.172.58 
[Fri Nov 13 14:00:02 2015] 301 1.internetwache.org ---> 95.143.172.58 
[Fri Nov 13 14:00:03 2015] 301 10.internetwache.org ---> 95.143.172.58 
[Fri Nov 13 14:00:04 2015] 301 11.internetwache.org ---> 95.143.172.58 
[Fri Nov 13 14:00:05 2015] 301 12.internetwache.org ---> 95.143.172.58 
[Fri Nov 13 14:00:06 2015] 301 13.internetwache.org ---> 95.143.172.58 
```

Taking care of the wildcard and filtering out 'false positives' would be very helpful. Basic idea of implementation:
- Request some non-existent subdomain (`sdfsdfsdf1337trolololo.domain.tld` and `asdasdasd.domain.tld`) and filter all matches with the same IP address. This again may lead to some false negatives (missing subdomains which point to the same IP), but in my opinion less damage is done.

**Comment by nahamsec** [comment]
Working on a solution for that as we speak. (very similar to your example). Will update soon! Thanks!

**Comment by nahamsec** [comment]
Here's the fix:

```
res = Net::HTTP.get_response(URI.parse(target))
            getCode = res.code
            temp_target = "http://ThereIsNoWayThisDomainExists1363635635353gdbdd"+targetURI
            temp_res = Net::HTTP.get_response(URI.parse(temp_target))
            ignore_code = temp_res.code


            ip_address = Resolv.getaddress targetURI

            if (getCode != ignore_code)
```

so ignore_code is the response code for ThereIsNoWayThisDomainExists1363635635353gdbdd.target.com 
so whatever that returns, will be ignored :)
